### PR TITLE
Update Send-Signal.ps1 to account for DST

### PR DESCRIPTION
**Pull request by jeffyates**

### CODE REVIEW

**Review by srazin — CHANGES_REQUESTED** [review]
are you suggesting a new flag to be passed in?
Could you please make sure that README addresses the new as well as existing flags.

**Comment by srazin** [comment]
BTW @jeffyates you are coding? @toddfrye we got a new resource! Let's restructure the roadmap to pull Jeff in as QA and Coder! :)

**Comment by jeffyates** [comment]
In testing the new Signal scripts, I noticed that the Windows Event (log)
time that was sent to iQ, showed as one hour later (PERC event) than the
actual time (event log). This is because the Windows server I'm on did not
account for DST in powershell (even though the actual time was right). So
all I've really done is do a check to see if that PC thinks it's Daylight
Savings Time. If False take the BaseUTCoffset, which is -5, and +1, to make
it -4. The rest of the $tzinfo line formats it, so it either comes out as
-0500 or -0400 depending.

New coding resource? LOL - don't get your hopes up! ;)


--jeff

**Comment by jeffyates** [comment]
@srazin The README is a user guideline and does not contain info about editing this particular script. This script also isn't necessarily something the user would edit. Advise.

**Comment by siosadmin** [comment]
After looking at this some more, the TimeZoneInfo class has a boolean you
might want to use in conjunction with IsDayLightSavingsTime(0). Your
current version has a bug where it will always add an hour to regions that
don't support DST, like UTC for example:



I would use something like this for your if logic. This way you figure out
if your local time zone even supports DST, and then make sure it isn't
currently DST before adding 1.

$tz = [TimeZoneInfo]::Local
if( $tz.SupportsDaylightSavingTime -And -Not $tz.IsDaylightSavingTime(0) )
{
    $tzinfo = (($tz.BaseUtcOffset.Hours) + 1).ToString("00") +
[Math]::abs($tz.BaseUtcOffset.Minutes).ToString("00")
} else {
    $tzinfo = $tz.BaseUtcOffset.Hours.ToString("00") +
[Math]::abs($tz.BaseUtcOffset.Minutes).ToString("00")
}

**Comment by jeffyates** [comment]
Valid point...let me investigate and rework.

**Review by srazin — APPROVED** [review]
make sense. Looks good.

**Pull request merged**
